options:
  env:
    - PROJECT_ROOT=source.baburke.net/baburke-services/gcloud-logger
    - GOOS=linux
    - GOARCH=amd64
steps:
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['get', '-u', 'cloud.google.com/go/logging']
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['install', '.']
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['test', '-v', './glogger']
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['test', '-v', 'main.go', 'main_test.go']
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['build', '-o', 'glogger.linux', 'main.go']

artifacts:
  objects:
    location: gs://net-baburke-services-artifacts/ostools
    paths:
      - glogger.linux
      - glogger-tmpfiles.conf
      - glogger.service
